import { test, expect, describe } from "bun:test";
import { join } from "node:path";
import {
  generateSnippetsModule,
  readSources,
  OUT_PATH,
  type SnippetSources,
} from "./build-snippets";

const REPO_ROOT = join(import.meta.dir, "../../..");

// ── generateSnippetsModule — header ──────────────────────────────────────────

describe("generateSnippetsModule — header", () => {
  test("starts with AUTO-GENERATED comment line", () => {
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: "codegraph content\n",
      AST_GREP_RULE_SNIPPET: "ast-grep content\n",
    };
    const output = generateSnippetsModule(sources);
    expect(output.startsWith("// AUTO-GENERATED by packages/atomic-sdk/script/build-snippets.ts\n")).toBe(true);
  });

  test("header includes regenerate hint with exact bun command", () => {
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: "a\n",
      AST_GREP_RULE_SNIPPET: "b\n",
    };
    const output = generateSnippetsModule(sources);
    expect(output).toContain("bun run --filter @bastani/atomic-sdk build:snippets");
  });

  test("header includes Source: docs/agent-snippets/*.md", () => {
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: "a\n",
      AST_GREP_RULE_SNIPPET: "b\n",
    };
    const output = generateSnippetsModule(sources);
    expect(output).toContain("Source: docs/agent-snippets/*.md");
  });
});

// ── generateSnippetsModule — exports ─────────────────────────────────────────

describe("generateSnippetsModule — export declarations", () => {
  test("contains export const CODEGRAPH_SNIPPET with JSON-stringified value", () => {
    const val = "hello codegraph\n";
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: val,
      AST_GREP_RULE_SNIPPET: "b\n",
    };
    const output = generateSnippetsModule(sources);
    expect(output).toContain(`export const CODEGRAPH_SNIPPET = ${JSON.stringify(val)};`);
  });

  test("contains export const AST_GREP_RULE_SNIPPET with JSON-stringified value", () => {
    const val = "hello ast-grep\n";
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: "a\n",
      AST_GREP_RULE_SNIPPET: val,
    };
    const output = generateSnippetsModule(sources);
    expect(output).toContain(`export const AST_GREP_RULE_SNIPPET = ${JSON.stringify(val)};`);
  });
});

// ── generateSnippetsModule — JSON.stringify safety ───────────────────────────

describe("generateSnippetsModule — JSON.stringify safety", () => {
  test("double-quotes, backslashes, and embedded newlines round-trip correctly", () => {
    const fixture = `line one\nhas "double quotes" and a backslash \\ here\n`;
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: fixture,
      AST_GREP_RULE_SNIPPET: "b\n",
    };
    const output = generateSnippetsModule(sources);

    // Extract the literal after `export const CODEGRAPH_SNIPPET = `
    const match = output.match(/export const CODEGRAPH_SNIPPET = ("(?:[^"\\]|\\[\s\S])*");/);
    expect(match).not.toBeNull();
    const literal = match![1];
    const parsed = JSON.parse(literal) as string;
    expect(parsed).toBe(fixture);
  });

  test("embedded newlines in AST_GREP_RULE_SNIPPET round-trip via JSON.parse", () => {
    const fixture = `rule:\n  pattern: foo\n  "key": "val"\n  back\\slash\n`;
    const sources: SnippetSources = {
      CODEGRAPH_SNIPPET: "a\n",
      AST_GREP_RULE_SNIPPET: fixture,
    };
    const output = generateSnippetsModule(sources);

    const match = output.match(/export const AST_GREP_RULE_SNIPPET = ("(?:[^"\\]|\\[\s\S])*");/);
    expect(match).not.toBeNull();
    const parsed = JSON.parse(match![1]) as string;
    expect(parsed).toBe(fixture);
  });
});

// ── OUT_PATH constant ─────────────────────────────────────────────────────────

describe("OUT_PATH", () => {
  test("equals exact repo-root-relative path", () => {
    expect(OUT_PATH).toBe(
      "packages/atomic-sdk/src/workflows/builtin/deep-research-codebase/helpers/snippets.generated.ts"
    );
  });
});

// ── readSources — integration against real repo ───────────────────────────────

describe("readSources — real repo", () => {
  test("returns both keys with non-empty strings", async () => {
    const sources = await readSources(REPO_ROOT);
    expect(typeof sources.CODEGRAPH_SNIPPET).toBe("string");
    expect(sources.CODEGRAPH_SNIPPET.length).toBeGreaterThan(0);
    expect(typeof sources.AST_GREP_RULE_SNIPPET).toBe("string");
    expect(sources.AST_GREP_RULE_SNIPPET.length).toBeGreaterThan(0);
  });

  test("CODEGRAPH_SNIPPET ends with \\n", async () => {
    const sources = await readSources(REPO_ROOT);
    expect(sources.CODEGRAPH_SNIPPET.endsWith("\n")).toBe(true);
  });

  test("AST_GREP_RULE_SNIPPET ends with \\n", async () => {
    const sources = await readSources(REPO_ROOT);
    expect(sources.AST_GREP_RULE_SNIPPET.endsWith("\n")).toBe(true);
  });

  test("CODEGRAPH_SNIPPET does not end with double newline (trimEnd applied)", async () => {
    const sources = await readSources(REPO_ROOT);
    expect(sources.CODEGRAPH_SNIPPET.endsWith("\n\n")).toBe(false);
  });

  test("AST_GREP_RULE_SNIPPET does not end with double newline (trimEnd applied)", async () => {
    const sources = await readSources(REPO_ROOT);
    expect(sources.AST_GREP_RULE_SNIPPET.endsWith("\n\n")).toBe(false);
  });
});
