/**
 * build-snippets.ts
 *
 * Generator: reads canonical Markdown snippet sources and emits a
 * generated TypeScript module at
 *   packages/atomic-sdk/src/workflows/builtin/deep-research-codebase/helpers/snippets.generated.ts
 *
 * Usage:
 *   bun run --filter @bastani/atomic-sdk build:snippets
 *   bun packages/atomic-sdk/script/build-snippets.ts
 */

import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "../../..");
const SOURCES = {
  CODEGRAPH_SNIPPET:       "docs/agent-snippets/codegraph.md",
  AST_GREP_RULE_SNIPPET:   "docs/agent-snippets/ast-grep-rule-development.md",
} as const;

export type SnippetSources = Record<keyof typeof SOURCES, string>;

const HEADER = `// AUTO-GENERATED by packages/atomic-sdk/script/build-snippets.ts
// DO NOT EDIT — run \`bun run --filter @bastani/atomic-sdk build:snippets\`
// Source: docs/agent-snippets/*.md
`;

export function generateSnippetsModule(sources: SnippetSources): string {
  const decls = (Object.keys(SOURCES) as Array<keyof typeof SOURCES>)
    .map((k) => `export const ${k} = ${JSON.stringify(sources[k])};`)
    .join("\n");
  return `${HEADER}\n${decls}\n`;
}

export async function readSources(repoRoot = REPO_ROOT): Promise<SnippetSources> {
  const out = {} as SnippetSources;
  for (const [k, rel] of Object.entries(SOURCES) as Array<[keyof typeof SOURCES, string]>) {
    out[k] = (await Bun.file(join(repoRoot, rel)).text()).trimEnd() + "\n";
  }
  return out;
}

export const OUT_PATH =
  "packages/atomic-sdk/src/workflows/builtin/deep-research-codebase/helpers/snippets.generated.ts";

export async function main(repoRoot = REPO_ROOT): Promise<void> {
  const sources = await readSources(repoRoot);
  const text = generateSnippetsModule(sources);
  await Bun.write(join(repoRoot, OUT_PATH), text);
}

if (import.meta.main) await main();
