import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

export { fs, os, path };
export { default as chalk } from "chalk";
export type { AgentMessage } from "@earendil-works/pi-agent-core";
export { getProviders, type Api, type AssistantMessage, type ImageContent, type Message, type Model, type OAuthProviderId, type OAuthSelectPrompt } from "@earendil-works/pi-ai/compat";
export type { AutocompleteItem, AutocompleteProvider, AutocompleteSuggestions, EditorComponent, Keybinding, KeyId, MarkdownTheme, OverlayHandle, OverlayOptions, SlashCommand } from "@earendil-works/pi-tui";
export { CombinedAutocompleteProvider, type Component, Container, fuzzyFilter, getCapabilities, hyperlink, Loader, type LoaderIndicatorOptions, Markdown, matchesKey, ProcessTerminal, Spacer, setKeybindings, Text, TruncatedText, TUI, visibleWidth } from "@earendil-works/pi-tui";
export { spawn, spawnSync } from "child_process";
export { APP_NAME, APP_TITLE, CHANGELOG_URL, ENV_OFFLINE, getEnvValue, setCodexFastModeEnvironmentSettings, getAgentDir, getAuthPath, getDebugLogPath, getDocsPath, getShareViewerUrl, VERSION } from "../../config.ts";
export { type AgentSession, type AgentSessionEvent, parseSkillBlock } from "../../core/agent-session.ts";
export { type AgentSessionRuntime, SessionImportFileNotFoundError } from "../../core/agent-session-runtime.ts";
export type { AutocompleteProviderFactory, EditorFactory, ExtensionCommandContext, ExtensionContext, ExtensionRunner, ExtensionUIContext, ExtensionUIDialogOptions, HostCustomUiState, HostCustomUiStateListener, ProjectTrustContext, ExtensionWidgetOptions } from "../../core/extensions/index.ts";
export { FooterDataProvider, type ReadonlyFooterDataProvider } from "../../core/footer-data-provider.ts";
export { type AppKeybinding, KeybindingsManager } from "../../core/keybindings.ts";
export type { ContextCompactionResult } from "../../core/compaction/index.ts";
export { defaultModelPerProvider, findExactModelReferenceMatch, resolveModelScope, resolveModelScopeWithDiagnostics, resolveRestoredModelReference } from "../../core/model-resolver.ts";
export { formatCodexFastModeModelLabel, hasSupportedCodexFastModeModel, shouldApplyCodexFastMode } from "../../core/codex-fast-mode.ts";
export { configureHttpDispatcher } from "../../core/http-dispatcher.ts";
export { DefaultPackageManager } from "../../core/package-manager.ts";
export { BUILT_IN_PROVIDER_DISPLAY_NAMES } from "../../core/provider-display-names.ts";
export type { ResourceDiagnostic } from "../../core/resource-loader.ts";
export { formatMissingSessionCwdPrompt, MissingSessionCwdError } from "../../core/session-cwd.ts";
export { type SessionContext, SessionManager } from "../../core/session-manager.ts";
export { BUILTIN_SLASH_COMMANDS, BUNDLED_EXTENSION_SLASH_COMMANDS } from "../../core/slash-commands.ts";
export type { SourceInfo } from "../../core/source-info.ts";
export { isInstallTelemetryEnabled } from "../../core/telemetry.ts";
export type { TruncationResult } from "../../core/tools/truncate.ts";
export { getChangelogPath, getEntriesForVersion, getNewEntries, normalizeChangelogLinks, parseChangelog } from "../../utils/changelog.ts";
export { copyToClipboard } from "../../utils/clipboard.ts";
export { combineQueuedMessagesForEditor, openExternalEditorForText, pasteClipboardImageToEditor } from "./chat-input-actions.ts";
export { parseGitUrl } from "../../utils/git.ts";
export { getCwdRelativePath } from "../../utils/paths.ts";
export { getPiUserAgent } from "../../utils/pi-user-agent.ts";
export { killTrackedDetachedChildren } from "../../utils/shell.ts";
export { recordTimeSinceReset } from "../../core/timings.ts";
export { ensureTool } from "../../utils/tools-manager.ts";
export { checkForNewPiVersion } from "../../utils/version-check.ts";
export { pickWhimsicalWorkingMessage } from "./whimsical-messages.ts";
export { ArminComponent } from "./components/armin.ts";
export { AssistantMessageComponent } from "./components/assistant-message.ts";
export { BashExecutionComponent } from "./components/bash-execution.ts";
export { BorderedLoader } from "./components/bordered-loader.ts";
export { BranchSummaryMessageComponent } from "./components/branch-summary-message.ts";
export { chatEntriesFromAgentMessages, renderChatMessageEntry, type ChatMessageEntry, type ChatMessageRenderOptions } from "./components/chat-message-renderer.ts";
export { addChatTranscriptEntry } from "./components/chat-transcript.ts";
export { ContextCompactionSummaryMessageComponent } from "./components/context-compaction-summary-message.ts";
export { CountdownTimer } from "./components/countdown-timer.ts";
export { CustomEditor } from "./components/custom-editor.ts";
export { CustomMessageComponent } from "./components/custom-message.ts";
export { DaxnutsComponent } from "./components/daxnuts.ts";
export { renderAtomicAnsiBanner } from "./components/atomic-banner.ts";
export { DynamicBorder } from "./components/dynamic-border.ts";
export { ContextWindowSelectorComponent } from "./components/context-window-selector.ts";
export { formatContextWindow } from "../../core/context-window.ts";
export { copilotApiBaseUrlFromToken, copilotCatalogCacheHost, copilotCatalogCachePath, fetchCopilotModelCatalog, readCopilotCatalogCache, setActiveCopilotModelCatalog, writeCopilotCatalogCache } from "../../core/copilot-model-catalog.ts";
export { EarendilAnnouncementComponent } from "./components/earendil-announcement.ts";
export { ExtensionEditorComponent } from "./components/extension-editor.ts";
export { ExtensionInputComponent } from "./components/extension-input.ts";
export { ExtensionSelectorComponent } from "./components/extension-selector.ts";
export { FastModeSelectorComponent } from "./components/fast-mode-selector.ts";
export { FooterComponent, UsageMeterComponent } from "./components/footer.ts";
export { formatKeyText, keyDisplayText, keyText } from "./components/keybinding-hints.ts";
export { LoginDialogComponent } from "./components/login-dialog.ts";
export { ModelSelectorComponent } from "./components/model-selector.ts";
export { type AuthSelectorProvider, OAuthSelectorComponent } from "./components/oauth-selector.ts";
export { ScopedModelsSelectorComponent } from "./components/scoped-models-selector.ts";
export { SessionSelectorComponent } from "./components/session-selector.ts";
export { SettingsSelectorComponent } from "./components/settings-selector.ts";
export { SkillInvocationMessageComponent } from "./components/skill-invocation-message.ts";
export { ToolExecutionComponent } from "./components/tool-execution.ts";
export { TreeSelectorComponent } from "./components/tree-selector.ts";
export { TrustSelectorComponent } from "./components/trust-selector.ts";
export { hasProjectConfigDir, hasProjectTrustInputs, hasTrustRequiringProjectResources, ProjectTrustStore } from "../../core/trust-manager.ts";
export { UserMessageComponent } from "./components/user-message.ts";
export { UserMessageSelectorComponent } from "./components/user-message-selector.ts";
export { getModelSearchText } from "./model-search.ts";
export { getAvailableThemes, getAvailableThemesWithPaths, getEditorTheme, getMarkdownTheme, getThemeByName, onThemeChange, setRegisteredThemes, stopThemeWatcher, Theme, theme } from "./theme/theme.ts";
export { InteractiveThemeController } from "./theme/theme-controller.ts";
