name: Publish Devcontainer Features

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - '.devcontainer/features/**'
  workflow_dispatch:

jobs:
  publish:
    if: >-
      github.event_name == 'workflow_dispatch'
      || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./.devcontainer/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
