name: Validate Devcontainer Features

on:
  pull_request:
    paths:
      - '.devcontainer/features/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate devcontainer-feature.json schemas
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./.devcontainer/features"
